server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1002
    driver-class-name: com.mysql.jdbc.Driver
userservice:
  ribbon:
    NFloadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
